/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_crackme_MainActivity */

#ifndef _Included_com_example_crackme_MainActivity
#define _Included_com_example_crackme_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_crackme_MainActivity
 * Method:    startgame
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_crackme_MainActivity_startgame
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_crackme_MainActivity
 * Method:    checkflag
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_crackme_MainActivity_checkflag
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
