/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_crackme_mActivity */

#ifndef _Included_com_example_crackme_mActivity
#define _Included_com_example_crackme_mActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_crackme_mActivity
 * Method:    check
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_crackme_mActivity_check
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_crackme_mActivity
 * Method:    a
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_crackme_mActivity_a
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
